---
title: "part2"
author: "nursenakocaturk"
date: "2023-12-10"
output: html_document
---

```{r}
library("readr")
library("dplyr")
library("taxa")
library("metacoder")
library("vegan")
```


```{r}
otu_data <- read.table("data/krakenuniq_abundance_matrix.txt", header = T, sep = "\t")

write.table(
  x = data.frame(OTU_ID = seq(1,nrow(otu_data)), 
                 Species = rownames(otu_data)), 
  file = "data/otu_metadata.txt", quote = F, row.names = F, sep = "\t")

rownames(otu_data) <- seq(1,nrow(otu_data))
#otu_data$OTU_ID <- seq(1,nrow(otu_data))
otu_data <- as_tibble(cbind(OTU_ID = seq(1,nrow(otu_data)), otu_data))
```


```{r}
tax_data <- read_tsv("data/otu_metadata.txt")
```

```{r}
sample_data <- read_csv2("data/metadata.csv")
```

```{r}
tax_data$OTU_ID <- as.character(tax_data$OTU_ID)
otu_data$OTU_ID <- as.character(otu_data$OTU_ID) 
otu_data <- left_join(otu_data, tax_data,
                      by = c("OTU_ID" = "OTU_ID")) 
print(otu_data)
```


```{r}

obj <- parse_tax_data(otu_data,
                      class_cols = "Species", 
                      class_sep = ";") 
print(obj)
```

```{r}
print(obj$data$tax_data)

```


```{r}
names(obj$data) <- "otu_counts"
#print(obj)
```



```{r}
obj$data$otu_counts <- obj$data$tax_data[c("taxon_id", "OTU_ID", sample_data$Sample)]
```

```{r}
print(obj)
```




## Manipulating taxonomic data


```{r}
print(sample_data)
```


```{r}
sample_data <- sample_data[sample_data$Sample == "ecotypes", ]
```


```{r}
library(dplyr)
sample_data <- filter(sample_data, Sample == "ecotypes")
```




```{r}
obj <- filter_taxa(obj, taxon_names != "")
print(obj)
```



```{r}
head(taxon_names(obj))
```


```{r}
head(all_names(obj), 20)
```

```{r}
length(all_names(obj))
```










